# Site settings
title: Lively Wallpaper
email: awoo.git@gmail.com
description: Lively Wallpaper is a free and open-source animated desktop wallpaper and screensaver software.
baseurl: "/lively-jekyll-website" # the subpath of your site, e.g. /blog
url: "https://rabbit-world.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: rocksdanister

# Build settings
markdown: kramdown
permalink: pretty

# GitHub Pages plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Multilingual settings
languages: ["en", "it"]
default_lang: "en"
exclude_from_localization: ["assets", "js", "styles", "media", "shaders"]
parallel_localization: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - temp/